version: "3.5"
services:
  postgres:
    image: postgres:14-alpine
    env_file: .env.docker
    ports:
      - 5432:5432
    networks:
      - lab
  redis:
    image: redis:6-alpine
    ports:
      - 127.0.0.1:6379:6379
    networks:
      - lab
  fileserver:
    image: nuxion/fileserver
    volumes:
      - ./fileserver.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 4444:4444
    networks:
      - lab
  control-plane:
    image: nuxion/labfunctions:0.8.0
    env_file: .env.docker
    command: >
      lab web --apps workflows,history,projects,events,runtimes -A --workers 1 -L
    ports:
      - 127.0.0.1:8000:8000
    environment:
      LF_SERVER: true
    networks:
      - lab
  lab-agent:
    image: nuxion/labfunctions:0.8.0
    env_file: .env.docker
    command: >
      lab agent -w 1 -q control,mch.default
      agent run --qnames cpu,build,control -m local/ba/example
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    networks:
      - lab
networks:
  lab: 
